language: rust
rust:
  - stable
os:
  - linux
  - osx

dist: trusty
sudo: required

cache: cargo

script:
  - cargo build --verbose --all-features
  - cargo test --verbose --all-features

branches:
  only:
    # Release tags
    - /^v\d+\.\d+\.\d+.*$/
    - test-release-tag-please-ignore
    - develop
